### ISSUE TITLE
Client crash when set item to top, right, or left slot of Alloy Furnace at MC1.14.4

### ISSUE THREAD

**Issue by feru4g** [Sinhika/Fusion#9]
Hello, your Simple Ores is very good MOD and I play thankfull.
Today, I know Fusion MOD and install, but Client crash when set item to top, right, or left slot of Alloy Furnace.

Crash-Report is bellow.

---- Minecraft Crash Report ----
// There are four lights!

Time: 20/05/19 12:18
Description: mouseReleased event handler

java.lang.NullPointerException: mouseReleased event handler
	at mod.alexndr.fusion.api.recipe.FusionRecipe.initLegalisms(FusionRecipe.java:60) ~[?:1.14.4-2.5.3.2] {re:classloading}
	at mod.alexndr.fusion.api.recipe.FusionRecipe.isCatalyst(FusionRecipe.java:90) ~[?:1.14.4-2.5.3.2] {re:classloading}
	at mod.alexndr.fusion.api.content.AbstractAlloyFurnaceTileEntity.isCatalyst(AbstractAlloyFurnaceTileEntity.java:142) ~[?:1.14.4-2.5.3.2] {re:classloading}
	at mod.alexndr.fusion.api.content.AbstractAlloyFurnaceTileEntity.access$100(AbstractAlloyFurnaceTileEntity.java:50) ~[?:1.14.4-2.5.3.2] {re:classloading}
	at mod.alexndr.fusion.api.content.AbstractAlloyFurnaceTileEntity$1.isItemValid(AbstractAlloyFurnaceTileEntity.java:95) ~[?:1.14.4-2.5.3.2] {re:classloading}
	at net.minecraftforge.items.SlotItemHandler.func_75214_a(SlotItemHandler.java:47) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:248) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:367) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:515) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:485) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4690/1231609529.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3847/2109706922.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99) ~[?:mc1.14.4-1.15] {re:classloading}
	at tamaized.aov.client.events.KeyHandler.callbackMouseButton(KeyHandler.java:158) ~[?:1.14-0.13.4] {re:classloading}
	at tamaized.aov.client.events.KeyHandler$$Lambda$4432/833662126.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at net.minecraft.client.MainWindow.func_216528_l(SourceFile:408) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:279) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_213227_b(Minecraft.java:947) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:911) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.16.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/1410186665.call(Unknown Source) [forge-1.14.4-28.2.16.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mod.alexndr.fusion.api.recipe.FusionRecipe.initLegalisms(FusionRecipe.java:60)
	at mod.alexndr.fusion.api.recipe.FusionRecipe.isCatalyst(FusionRecipe.java:90)
	at mod.alexndr.fusion.api.content.AbstractAlloyFurnaceTileEntity.isCatalyst(AbstractAlloyFurnaceTileEntity.java:142)
	at mod.alexndr.fusion.api.content.AbstractAlloyFurnaceTileEntity.access$100(AbstractAlloyFurnaceTileEntity.java:50)
	at mod.alexndr.fusion.api.content.AbstractAlloyFurnaceTileEntity$1.isItemValid(AbstractAlloyFurnaceTileEntity.java:95)
	at net.minecraftforge.items.SlotItemHandler.func_75214_a(SlotItemHandler.java:47)
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:248)
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:367)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:515)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:485)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88)
	at net.minecraft.client.MouseHelper$$Lambda$4690/1231609529.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: mod.alexndr.fusion.client.gui.FusionFurnaceScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86)
	at net.minecraft.client.MouseHelper$$Lambda$3847/2109706922.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99)
	at tamaized.aov.client.events.KeyHandler.callbackMouseButton(KeyHandler.java:158)
	at tamaized.aov.client.events.KeyHandler$$Lambda$4432/833662126.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.minecraft.client.MainWindow.func_216528_l(SourceFile:408)
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:279)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Ferusuzu'/1142, l='MpServer', x=12.60, y=153.06, z=-1881.65]]
	Chunk stats: Client Chunk Cache: 961, 625
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-107,72,48), Chunk: (at 5,4,0 in -7,3; contains blocks -112,0,48 to -97,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1349464 game time, 304900 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/1410186665.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7192045032 bytes (6858 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.16.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.16.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.16
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.16-client.jar Minecraft {minecraft@1.14.4 DONE}
		spg_mod_1.0.13.jar SPG MOD {spgmod@1.0.0 DONE}
		ComPatchedStorage-1.14.4-2.1.4.jar ComPatchedStorage {compatchedstorage@2.1.4 DONE}
		AoV-1.14-0.13.4.jar Angel of Vengeance {aov@1.14-0.13.4 DONE}
		SlashBlade-1.14-0.0.10.jar Slash Blade {slashblade@0.0.10 DONE}
		japaricraftmod-1.14.4-0.2.0.jar JapariCraftMod {japaricraftmod@0.2.0 DONE}
		paintings-1.14.4-6.0.1.5.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		findme-1.14.4-1.1.0.13.jar Find Me {findme@NONE DONE}
		SpartanShields-1.14.4-2.0.0.jar Spartan Shields {spartanshields@2.0.0 DONE}
		Neat+1.5-19.jar Neat {neat@1.5-19 DONE}
		Xaeros_Minimap_20.9.0_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.9.0 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		placeableitems-4.0.0.jar Placeable Items {placeableitems@4.0 DONE}
		Controlling-5.0.6.jar Controlling {controlling@5.0.6 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		themidnight-0.4.7.jar The Midnight {midnight@0.4.7 DONE}
		SpartanWeaponry-1.14.4-2.0.0-beta-1.jar Spartan Weaponry {spartanweaponry@2.0.0 beta 1 DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		environmentalcreepers-forge-1.14.4-1.6.0.jar Environmental Creepers {environmentalcreepers@1.6.0 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		VTweaks-1.14.4-3.1.6.jar V-Tweaks {vtweaks@3.1.2 DONE}
		NBTEdit-0.8.2.jar NBTEdit {nbtedit@0.8.1 DONE}
		Fusion-1.14.4-2.5.3.2.jar Fusion {fusion@1.14.4-2.5.3.2 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		ex_blades-1.0.jar SlashBlade Addon {ex_blades@1.0 DONE}
		FpsReducer-mc1.14.4-1.15.jar FPS Reducer {fpsreducer@mc1.14.4-1.15 DONE}
		CarryOn+MC1.14.4+v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		JustEnoughResources-1.14.4-0.10.1.76.jar Just Enough Resources {jeresources@0.10.1.76 DONE}
		FriendlyFire-1.14.4-3.0.1.jar FriendlyFire {friendlyfire@3.0.1 DONE}
		meshi-0.3.jar Meshi_Mod {meshi@0.3 DONE}
		forge-1.14.4-28.2.16-universal.jar Forge {forge@28.2.16 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		CosmeticArmorReworked-1.14.4-v3.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v3 DONE}
		NetherEx-1.14.4-3.0.3.jar NetherEx {netherex@3.0.3 DONE}
		LibraryEx-1.14.4-2.0.3.jar LibraryEx {libraryex@2.0.3 DONE}
		SimpleOres2-1.14.4-2.0.9.0.jar Simple Ores {simpleores@1.14.4-2.0.9.0 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
	Launched Version: 1.14.4-forge-28.2.16
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: 日本語 (日本)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by Sinhika** [comment]
Fixed in 1.15.2 with commit 9a42c50047117a61fb85ccf15574c7330b099dd7.
Fixed in 1.14.4 with commit 58aa06a3aa53e67b55611cfc3409d3c72c0c4954.

Updates to be posted soon to CurseForge.
